catalogues: [personal]
description: Some description about this sample
descriptor_extension: yml
maintainer: Jonas Manuel
name: jonas_test
publish_to: [personal]
repo_url: https://github.com/Jmanuel4SandMan/son-test-project
vendor: eu.sonata-nfv.package
version: '0.4'
