catalogues: [personal]
description: Some description about this sample
descriptor_extension: yml
maintainer: Jonas
name: son_test_project
publish_to: [personal]
repo_url: https://github.com/Jmanuel4SandMan/son-test-project.git
vendor: eu.sonata-nfv.package
version: '0.4'
